In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

c:\Users\spradkyl\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
Path.cwd()

WindowsPath('c:/Users/spradkyl/OneDrive - Texas Association of School Boards/Documents/Code/ML Zoomcamp/Homework/2025/01-intro')

### Q1. Pandas version
What's the version of Pandas that you installed?

In [3]:
#1)
pd.__version__

'2.2.2'

### Q2. Records count
How many records are in the dataset?

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [70]:
#2)
print(f'Total Records: {df.shape[0]}')

Total Records: 9704


### Q3. Fuel types
How many fuel types are presented in the dataset?

In [10]:
#3.)
df.fuel_type.unique().shape[0]

2

In [5]:
df.fuel_type.nunique()

2

### Q4. Missing values
How many columns in the dataset have missing values?

In [19]:
#4)
missing_columns = df.isna().any().sum()
print(missing_columns)

4


### Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [22]:
#5)
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(3)


23.759

In [23]:
#5)
df.query("origin == 'Asia'")['fuel_efficiency_mpg'].max().round(3)

23.759

### Q6. Median value of horsepower
1. Find the median value of horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.


Has it changed?

Yes, it increased
Yes, it decreased
No

In [ ]:
# Finding the median Horsepower
df['horsepower'].median()

149.0

In [ ]:
# most frequent horsepower
df['horsepower'].mode()[0]

152.0

In [ ]:
# replace n/a with the mode values
df['horsepower'] = df['horsepower'].fillna(152)

### Q7. Sum of weights
1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [46]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0       152.0     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [58]:
#1. Select all the cars from Asia
#2. Select only columns vehicle_weight and model_year
#3. Select the first 7 values
df2 = df.query("origin == 'Asia'")[['vehicle_weight','model_year']][0:7]
df2

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [59]:
#4. Get the underlying NumPy array. Let's call it X.
X = np.array(df2)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [60]:
#5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

# Transpose of X
XT = X.T

# Matrix-Matrix Multiplication
XTX = XT.dot(X)
XTX

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [61]:
#6. Invert XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [62]:
#7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [63]:
#8a. Multiply the inverse of XTX with the transpose of X 
U = XTX_inv.dot(XT)
U

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [67]:
#8b. then multiply the result by y. Call the result w.
w = U.dot(y)
w

array([0.01386421, 0.5049067 ])

In [68]:
#9. What's the sum of all the elements of the result?
w.sum()

0.5187709081074001